context.properties = {
    default.clock.min-quantum = 1024
    default.clock.quantum = 1024
}

context.properties.rules = [
    {
        matches = [ { node.driver = true } ]
        actions = {
            update-props = {
                clock.force-quantum = 1024
            }
        }
    }
]
