[General]
#################### General ####################

ScreenWidth="1366"
ScreenHeight="768"
ScreenPadding=""

Font="Noto Sans"
FontSize=""

KeyboardSize="0.4"

RoundCorners="20"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd, d of MMMM"

HeaderText="Welcome!"

#################### Background ####################

BackgroundPlaceholder=""
Background="/usr/share/sddm/backgrounds/sddm_wallpaper.jpg"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.0"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

HeaderTextColor="#ffffff"
DateTextColor="#ffffff"
TimeTextColor="#ffffff"

FormBackgroundColor="#444444"
BackgroundColor="#444444"
DimBackgroundColor="#444444"

LoginFieldBackgroundColor="#ffffff"
PasswordFieldBackgroundColor="#ffffff"
LoginFieldTextColor="#ffffff"
PasswordFieldTextColor="#ffffff"
UserIconColor="#ffffff"
PasswordIconColor="#ffffff"

PlaceholderTextColor="#ffffff"
WarningColor="#fb884f"

LoginButtonTextColor="#ffffff"
LoginButtonBackgroundColor="#ffffff"
SystemButtonsIconsColor="#F8F8F2"
SessionButtonTextColor="#F8F8F2"
VirtualKeyboardButtonTextColor="#F8F8F2"

DropdownTextColor="#ffffff"
DropdownSelectedBackgroundColor="#fb884f"
DropdownBackgroundColor="#444444"

HighlightTextColor="#ffffff"
HighlightBackgroundColor="#fb884f"
HighlightBorderColor="#fb884f"

HoverUserIconColor="#fb884f"
HoverPasswordIconColor="#fb884f"
HoverSystemButtonsIconsColor="#fb884f"
HoverSessionButtonTextColor="#fb884f"
HoverVirtualKeyboardButtonTextColor="#fb884f"

#################### Form ####################

PartialBlur="true"
FullBlur="false"
BlurMax="64"
Blur="1.0"

HaveFormBackground="false"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="left"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

UseRealName="false"
ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="false"
AllowEmptyPassword="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
