require("signal.battery")
require("signal.brightness")
require("signal.volume")
require("signal.cpu")
require("signal.ram")
require("signal.todo")
require("signal.weather")
require("signal.playerctl")
require("signal.network")
require("signal.uptime")
require("signal.temperature")
pcall(require, "signal.disk")
pcall(require, "ui.widgets.resources")