local lock_screen = require("ui.lockscreen")
lock_screen.init()

require("ui.bar")
require("ui.dashboard")
require("ui.decorations")
require("ui.notifs")
require("ui.tooltip")
require("ui.widgets.desktop_widget")
require("ui.widgets.desktop_sysmon")
require("ui.widgets.desktop_music")
--require("ui.widgets.desktop_weather")
--require("ui.sidebar")
--require("ui.widgets.music_widget")
